// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSW2xPpBCae67yDOP-mQdnkEboSxk8mE',
    appId: '1:628110528380:web:8510927988b2450188def9',
    messagingSenderId: '628110528380',
    projectId: 'grocery-app-818d7',
    authDomain: 'grocery-app-818d7.firebaseapp.com',
    storageBucket: 'grocery-app-818d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9j3XG0VuB2OPTz9iD-fx5T9BjvVsgQs',
    appId: '1:628110528380:android:b470db62f7aa384888def9',
    messagingSenderId: '628110528380',
    projectId: 'grocery-app-818d7',
    storageBucket: 'grocery-app-818d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoAZDAVz2PvsVovCYE-Wc3fRkEQYskRds',
    appId: '1:628110528380:ios:17f72d18384c6e5388def9',
    messagingSenderId: '628110528380',
    projectId: 'grocery-app-818d7',
    storageBucket: 'grocery-app-818d7.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );
}
